### ISSUE TITLE
SSL certificate > Renew should restart Nginx

### ISSUE THREAD

**Issue by blavenie** [sumaris-net/sumaris-ansible#1]
After a cert renew, nginx should be restarted.

**Comment by blavenie** [comment]
In read on [this doc](https://skarlso.github.io/2018/01/23/nginx-certbot-ansible/) : 
```
- name: Generate Certificate for Domains
  shell: ./certbot-auto --authenticator standalone --installer nginx -d '{{ domain_example }}' -d '{{ domain_wiki }}' -d '{{ domain_nagios }}' --email example@gmail.com --agree-tos -n --no-verify-ssl --pre-hook "sudo systemctl stop nginx" --post-hook "sudo systemctl start nginx" --redirect
  args:
    chdir: /opt/letsencrypt
```

=> Try to add argument `--installer nginx` to letsencrypt renewal
